name: NextEnchant
main: com.Nepian.NextEnchant.Main
version: 0.1
author: Nepian
commands:
  nextenchant:
    prmission: NextEnchant.enchantlevelup
    usage: /<command> <enchantment>
    aliases:
    - nc